# Generated by Django 3.1.4 on 2020-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
